#!/bin/bash

set -o errexit
set -o pipefail
set -o nounset

if [ "${SERVER_ROLE}" == "ws" ]; then
  python main.py
fi


if [ "${SERVER_ROLE}" == "prod" ]; then
  uvicorn --host 0.0.0.0 --port "${PORT}" --log-level=debug --interface wsgi main_prod:flask_app;
fi

